/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/inventory': RouteRecordInfo<
      '/inventory',
      '/inventory',
      Record<never, never>,
      Record<never, never>,
      | '/inventory/'
      | '/inventory/ai-forecasting/'
      | '/inventory/products/'
      | '/inventory/reports/'
    >,
    '/inventory/': RouteRecordInfo<
      '/inventory/',
      '/inventory',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/inventory/ai-forecasting/': RouteRecordInfo<
      '/inventory/ai-forecasting/',
      '/inventory/ai-forecasting',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/inventory/products/': RouteRecordInfo<
      '/inventory/products/',
      '/inventory/products',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/inventory/reports/': RouteRecordInfo<
      '/inventory/reports/',
      '/inventory/reports',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/purchasing': RouteRecordInfo<
      '/purchasing',
      '/purchasing',
      Record<never, never>,
      Record<never, never>,
      | '/purchasing/'
    >,
    '/purchasing/': RouteRecordInfo<
      '/purchasing/',
      '/purchasing',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/inventory.vue': {
      routes:
        | '/inventory'
        | '/inventory/'
        | '/inventory/ai-forecasting/'
        | '/inventory/products/'
        | '/inventory/reports/'
      views:
        | 'default'
    }
    'src/pages/inventory/index.vue': {
      routes:
        | '/inventory/'
      views:
        | never
    }
    'src/pages/inventory/ai-forecasting/index.vue': {
      routes:
        | '/inventory/ai-forecasting/'
      views:
        | never
    }
    'src/pages/inventory/products/index.vue': {
      routes:
        | '/inventory/products/'
      views:
        | never
    }
    'src/pages/inventory/reports/index.vue': {
      routes:
        | '/inventory/reports/'
      views:
        | never
    }
    'src/pages/purchasing.vue': {
      routes:
        | '/purchasing'
        | '/purchasing/'
      views:
        | 'default'
    }
    'src/pages/purchasing/index.vue': {
      routes:
        | '/purchasing/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
